apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-extra-resources
parameters:
- name: JUPYTERHUB_NAMESPACE
  value: ""
  required: true
- name: JUPYTERHUB_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${JUPYTERHUB_APPLICATION}-res
    namespace: ${JUPYTERHUB_NAMESPACE}
    labels:
      app: ${JUPYTERHUB_APPLICATION}-${JUPYTERHUB_NAMESPACE}
      spawner: learning-portal
  data:
    extra_resources.json: |-
      {
        "kind": "List",
        "apiVersion": "v1",
        "items": [
          {
              "kind": "SecurityContextConstraints",
              "apiVersion": "security.openshift.io/v1",
              "metadata": {
                  "name": "${project_namespace}-redis",
                  "labels": {
                    "app": "${JUPYTERHUB_APPLICATION}-${JUPYTERHUB_NAMESPACE}",
                    "project": "${project_namespace}"
                  }
              },
              "priority": 888,
              "allowedCapabilities": [
                  "SYS_RESOURCE"
              ],
              "seLinuxContext": {
                  "type": "RunAsAny"
              },
              "runAsUser": {
                  "type": "RunAsAny"
              },
              "users": [
                  "system:serviceaccount:${project_namespace}:redis-enterprise-operator",
                  "system:serviceaccount:${project_namespace}:redis-enterprise"
              ]
          },
          {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
              "name": "redis-enterprise"
            }
          },
          {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
              "name": "redis-enterprise-operator"
            }
          },
          {
            "kind": "RoleBinding",
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "metadata": {
              "name": "redis-enterprise-operator"
            },
            "subjects": [
              {
                "kind": "ServiceAccount",
                "name": "redis-enterprise-operator",
                "namespace": "${project_namespace}"
              }
            ],
            "roleRef": {
              "kind": "ClusterRole",
              "apiGroup": "rbac.authorization.k8s.io",
              "name": "redis-enterprise-operator"
            }
          },
          {
            "apiVersion": "apps/v1beta1",
            "kind": "Deployment",
            "metadata": {
              "name": "redis-enterprise-operator"
            },
            "spec": {
              "replicas": 1,
              "selector": {
                "matchLabels": {
                  "name": "redis-enterprise-operator"
                }
              },
              "template": {
                "metadata": {
                  "labels": {
                    "name": "redis-enterprise-operator"
                  }
                },
                "spec": {
                  "serviceAccount": "redis-enterprise-operator",
                  "containers": [
                    {
                      "name": "redis-enterprise-operator",
                      "image": "redislabs/operator:498_f987b08.rhel7",
                      "command": [
                        "redis-enterprise-operator"
                      ],
                      "imagePullPolicy": "Always",
                      "env": [
                        {
                          "name": "WATCH_NAMESPACE",
                          "valueFrom": {
                            "fieldRef": {
                              "fieldPath": "metadata.namespace"
                            }
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        ]
      }
